#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

## MULTI-MONITOR CONFIGURATION ##
bspc monitor eDP-1 -d 1 2 3 4 5 6 7

# Window Spacing/Control
bspc config border_width	2
bspc config window_gap      19
bspc config top_padding		18
bspc config bottom_padding	18
bspc config left_padding    0
bspc config right_padding	0
bspc config split_ratio          0.50
bspc config borderless_monocle   false
bspc config gapless_monocle      false 
bspc config focus_follows_pointer	false
bspc config border_radius   17
bspc config automatic_scheme	alternate
bspc config removal_adjustment	false

bspc rule -r "*:*"
bspc rule -a Wpg:wpg state=floating # wpgtk
bspc rule -a pentablet:pentablet state=floating # Xp-Pen tablet driver
bspc rule -a Pavucontrol:pavucontrol state=floating # Audio controls
bspc rule -a cinebench.exe state=floating 
bspc rule -a Eog:eog state=floating # Image viewer
bspc rule -a steam_app_314650:steam_app_314650 monitor=^1 state=fullscreen # Space Engine
bspc rule -a Qalculate-gtk:qalculate-gtk state=floating 
bspc rule -a Tk:tk state=floating # DF Lazy Newb Pack
bspc rule -a Nm-connection-editor:nm-connection-editor state=floating
bspc rule -a Blueman-manager:blueman-manager state=floating # Bluetooth
bspc rule -a battle.net.exe:battle.net.exe state=floating

# External rules invocation
bspc config external_rules_command ~/.config/bspwm/scripts/external_rules.sh

## COMPSITOR STARTUP ##
picom -b --experimental-backend --config ~/.config/picom/picom.conf &

## COLOR CONTROL ##
bash /home/taritha/.config/bspwm/bspwm_colors.sh & # Loads colors for bspwm from wpgtk/pywal (borders and preselection mostly

# Load autorandr
autorandr default &
