#!usr/bin/env sh

#
# wm independent hotkeys
#

# terminal emulator
super + Return
	kitty

# program launcher
super + @space
	bash /home/taritha/.config/rofi/scripts/appsmenu.sh

super + alt + @space
	bash /home/taritha/.config/rofi/scripts/runmenu.sh

super + p
	bash /home/taritha/.config/rofi/scripts/powermenu.sh

#
# Show clipboard history
#
super + c
	rofi -modi "clipboard:greenclip print" -p "fooba" -show clipboard -theme themes/centermenu.rasi

#
# Show settings menu
#
super + o
	bash /home/taritha/.config/rofi/scripts/menu.sh

# make sxhkd reload its configuration files:
super + Escape
	pkill -USR1 -x sxhkd

#
# bspwm hotkeys
#

# quit/restart bspwm
super + alt + {q,r}
	bspc {quit,wm -r}

# close and kill
super + {_,shift + }q
	bspc node -{c,k}

# alternate between the tiled and monocle layout
super + m
	bspc desktop -l next

# send the newest marked node to the newest preselected node
super + y
	bspc node newest.marked.local -n newest.!automatic.local

# swap the current node and the biggest window
super + g
	bspc node -s biggest.window

#
# state/flags
#

# set the window state
super + {t,shift + t,s,f}
	bspc node -t {tiled,pseudo_tiled,floating,fullscreen}

# set the node flags
super + ctrl + {m,x,y,z}
	bspc node -g {marked,locked,sticky,private}

#
# focus/swap
#

# focus the node in the given direction
super + {_,shift + }{h,j,k,l}
	bspc node -{f,s} {west,south,north,east}

# focus the node for the given path jump
super + {p,b,comma,period}
	bspc node -f @{parent,brother,first,second}

# focus the next/previous window in the current desktop
super + {_,shift + }v
	bspc node -f {next,prev}.local.!hidden.window

# focus the next/previous desktop in the current monitor
super + ctrl + {Left,Right}
	bspc desktop -f {prev,next}.local

# focus the last node/desktop
super + {grave,Tab}
	bspc {node,desktop} -f last

# focus the older or newer node in the focus history
super + {o,i}
	bspc wm -h off; \
	bspc node {older,newer} -f; \
	bspc wm -h on

# focus or send to the given desktop
super + {_,shift + }{1-9,0}
	bspc {desktop -f,node -d} '^{1-9,10}'

#
# preselect
#

# preselect the direction
super + {Left,Down,Up,Right}
	bspc node -p {west,south,north,east}

# preselect the ratio
super + ctrl + {1-9}
	bspc node -o 0.{1-9}

# cancel the preselection for the focused node
ctrl + Escape
	bspc node -p cancel

# cancel the preselection for the focused desktop
super + ctrl + shift + space
	bspc query -N -d | xargs -I id -n 1 bspc node id -p cancel

# Move current window to preselected spot
super + ctrl + space
	bspc node -n last.!automatic

#
# move/resize
#

# expand a window by moving one of its side outward
super + alt + {h,j,k,l}
	bspc node -z {left -20 0,bottom 0 20,top 0 -20,right 20 0}

# contract a window by moving one of its side inward
super + alt + shift + {h,j,k,l}
	bspc node -z {right -20 0,top 0 20,bottom 0 -20,left 20 0}

# move a floating window
super + shift + {h,j,k,l}
	bspc node -v {-20 0,0 20,0 -20,20 0}


#
# Screenshots
# 
Print
	gnome-screenshot -i

alt + Print
	gnome-screenshot -c -d 1 -a

#
# Choose a new, random wallpaper
#
super + w
	wpg -m

#
# Visibility toggle using lapav script from https://github.com/shubham-cpp/lapav (TODO: Get this working in some form)
#

# Hide the focused window in a saved order
super + a
	~/.config/bspwm/scripts/bspc-ordered-hide.sh hide

# Unhide the hidden windows in order (shift lets you choose with rofi)
super + {_,shift +} d
	{~/.config/bspwm/scripts/bspc-ordered-hide.sh unhide --focus, ~/.config/bspwm/scripts/bspc-unhide-menu.sh --all}

#
# Lock screen
#
alt + shift + x
	betterlockscreen -l dim

#
# Reload polybar when it acts dumb
#
super + r
	bash ~/.config/polybar/launch.sh

#
# Dunst thingies
#
super + x
	dunstctl close

super + shift + x
	dunstctl close-all

super + n
	dunstctl history-pop

#
# Find currently open window, go to it, and focus on it
#
super + {_,shift +} z
	bash /home/taritha/.config/rofi/scripts/goto_window.sh

super + shift + y
	bash /home/taritha/.config/rofi/scripts/powermenu.sh