#!usr/bin/env sh

# Show help/keybind menu (this menu lol)
super + slash
	bash ~/.config/rofi/scripts/sxhkd-keys.sh

# terminal emulator
super + Return
	kitty

# Close spotify eww submenu
Pause
	eww --config ~/.config/eww/bars/ close spotify-window

# reload keybind config (sxhkd)
super + Escape
	pkill -USR1 -x sxhkd

# system settings
super + o
	bash ~/.config/rofi/scripts/menu.sh

# power menu
super + p
	bash ~/.config/rofi/scripts/powermenu.sh

# program launcher
super + @space
	bash ~/.config/rofi/scripts/appsmenu.sh

# run menu
super + alt + @space
	bash ~/.config/rofi/scripts/runmenu.sh

# clipboard history
super + c
	rofi -modi "clipboard:greenclip print" -p "fooba" -show clipboard -theme themes/centermenu.rasi

# switch to a new, random wallpaper
super + w
	wpg -m

# reload eww widgets when they act dumb
super + r
	~/.config/bspwm/scripts/load_eww.sh

# ultra reload eww when it REALLY acts up
super + shift + r
	~/.config/bspwm/scripts/load_eww.sh --kill

# quit/restart bspwm
super + alt + {q,r}
	bspc {quit,wm -r}

# close and kill focused window
super + {_,shift + }q
	bspc node -{c,k}

# set the window state
super + {t,shift + t,s,f}
	bspc node -t {tiled,pseudo_tiled,floating,fullscreen}

# focus on next or previous desktop
super + ctrl + {Left,Right}
	bspc desktop -f {prev,next}.local

# focus or send to the given desktop
super + {1-9,0}
	bspc node -d '^{1-9,10}' --follow

# send and focus to given desktop
super + alt + {1-9,0}
	bspc node -d '^{1-9,10}'

# focus the node in the given direction
super + {_,alt + }{Left,Down,Up,Right}
	bspc node -{f,s} {west,south,north,east}

# preselect the direction
super + shift + {Left,Down,Up,Right}
	bspc node -p {west,south,north,east}

# Expand/contract a window by moving one of its side outward/inward
super + b : {Left,Down,Up,Right}
	~/.config/sxhkd/scripts/resize_window.sh {1,2,3,4}

# Rotate tree
super + {l,j}
	bspc node @/ -C {forward,backward}

# cancel the preselection for the focused node
ctrl + Escape
	bspc node -p cancel

# move current window to preselected spot
ctrl + space
	bspc node -n last.!automatic

# open screenshot app
Print
	gnome-screenshot -i

# screenshot selection; save to clipboard
alt + Print
	gnome-screenshot -c -d 1 -a

# hide the focused window in a saved order
super + a
	~/.config/bspwm/scripts/bspc-ordered-hide.sh hide

# unhide the hidden windows in order (or with rofi)
super + {_,shift +} d
	{~/.config/bspwm/scripts/bspc-ordered-hide.sh unhide --focus, ~/.config/bspwm/scripts/bspc-unhide-menu.sh --all}

# lock screen
alt + shift + x
	betterlockscreen -l dim

# close last notification
super + x
	dunstctl close

# close all notifications
super + shift + x
	dunstctl close-all

# show last notification in history
super + n
	dunstctl history-pop

# find currently open window, go to it, and focus on it
super + z
	bash ~/.config/rofi/scripts/goto_window.sh

# play-pause media key
XF86AudioPlay
	playerctl play-pause

# next media key
XF86AudioNext
	playerctl next

# previous media key
XF86AudioPrev
	playerctl previous

# stop media key
XF86AudioStop
	playerctl -a stop

# mute media key
XF86AudioMute
	pamixer -t && ~/.config/eww/indicators/scripts/volume.sh

# vol down media key
XF86AudioLowerVolume
	pamixer -d 2 && ~/.config/eww/indicators/scripts/volume.sh

# vol up media key
XF86AudioRaiseVolume
	pamixer -i 2 && ~/.config/eww/indicators/scripts/volume.sh

# raise brightness
XF86MonBrightnessUp
	python ~/.config/eww/indicators/scripts/bright_keyhandler.py

# lower brightness
XF86MonBrightnessDown
	python ~/.config/eww/indicators/scripts/bright_keyhandler.py

# right click menu
~button3
	! bspc query -D -n pointed.local && echo -e "$(cat ~/.config/jgmenu/menu.txt)" | jgmenu --simple
